
rootLogger=INFO,LOGFILE

appender.file.type = File
appender.file.name = LOGFILE
appender.file.fileName = src/main/java/com/academy/course/hibernateDao/files/log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = [%-10level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %C{1} - %msg%n
appender.file.filter.threshold.type = ThresholdFilter
appender.file.filter.threshold.level = info